name: testing

on:
  push:
    branches:
      - test

jobs:

# Do something

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      
      - run: ls
