#Validate, Format, checkov security scan, Upload results to GHAS
name: 'Terraform Unit Tests'

on:
  push:
    paths: 
      - "TerraformPractice"
      - ".github/workflows/tf_*.yml"
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: environment
        description: Github environment defines the Azure subscription to be used for deploying resources
        required: true
        default: FreeTrail
        
#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: read
  security-events: write
  
jobs:
  terraform-unit-tests-job:
    name: 'Terraform Unit Tests'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac-terraform
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init - no backend
      run: terraform init -backend=false

    # Validate terraform files
    - name: Terraform Validate
      run: terraform validate

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check -recursive
	  #continue-on-error: true
    
    # Perform a security scan of the terraform code using checkov
    - name: Run Checkov action
      id: checkov
      uses: bridgecrewio/checkov-action@master
      continue-on-error: true
      with: 
        framework: terraform
      

    # Upload results to GitHub Advanced Security
    - name: Upload SARIF file
      if: success() || failure()
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
        category: checkov
